### ISSUE TITLE
Compiled

### ISSUE THREAD

**Issue by Squall789** [Silvris/MH-Tools-and-Scripts#1]
Hi, sorry, I'm not great at python, I have the required installed files but the python script kicks out the following error regardless

```
The filename, directory name, or volume label syntax is incorrect.
Traceback (most recent call last):
  File "MHStories2ARCExtract.py", line 315, in <module>
    readARC(open(arg,'rb'))
FileNotFoundError: [Errno 2] No such file or directory: ''
Press any key to continue . . .
```

I'm not entirely sure what I'm doing wrong.
Would it be possible, if its no trouble, to compile it into an exe or a drag and drop, if that possible, if not I'd be fine with this being explained honestly, that'd be great.

**Comment by dtlnor** [comment]
> Hi, sorry, I'm not great at python, I have the required installed files but the python script kicks out the following error regardless
> 
> ```
> The filename, directory name, or volume label syntax is incorrect.
> Traceback (most recent call last):
>   File "MHStories2ARCExtract.py", line 315, in <module>
>     readARC(open(arg,'rb'))
> FileNotFoundError: [Errno 2] No such file or directory: ''
> Press any key to continue . . .
> ```
> 
> I'm not entirely sure what I'm doing wrong.
> Would it be possible, if its no trouble, to compile it into an exe or a drag and drop, if that possible, if not I'd be fine with this being explained honestly, that'd be great.
use `MHStories2ARCExtract.bat`, its drag and drop

**Comment by Silvris** [comment]
As dtlnor said, the ".bat" can be used to drag and drop for opening files.
